# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='list',
        ),
    ]
